### ISSUE TITLE
Name option not fucntioning

### ISSUE THREAD

**Issue by IamGPIO** [paulhayes/web-3d-model-customiser#10]
Hi all, 

I cant get the Name option to function. I have tried in firefox & Chrome to no avail. Can anyone confirm?

Thanks

**Comment by sebleedelisle** [comment]
I seem to have broken this in the last update. Bear with me!

**Comment by sebleedelisle** [comment]
Should be fixed now, sorry about that! #11

**Comment by IamGPIO** [comment]
Great, thanks so much. Great work btw!!
