### ISSUE TITLE
Option to increase spacing between bands

### ISSUE THREAD

**Issue by billt79** [paulhayes/web-3d-model-customiser#16]
This would be really useful for people wanting to print multiples with a larger nozzle diameter

**Comment by owennewo** [comment]
+1, printing a stack with layer height of 0.4 (0.6 nozzle) ends up with fused bands

**Comment by Vegsaad** [comment]
I have also had problems with welding when using larger nozzle sizes. Perhaps if the nozzle size or gap size was an input this would be useful for those trying to print as fast as possible overnight.

**Comment by sebleedelisle** [comment]
Currently being tested in the dev deployment : http://modsebleedev.netlify.com - can you test and let me know how it works?

**Comment by Vegsaad** [comment]
Hi Seb,

 

Thanks for your update I will test asap but at the moment I am out of filament – just finished 60+ face shields may get a resupply on Monday.

Was getting up in the night to n alarm to reset my bed so this will be a game changer for me.

 

Thanks again

David Glass

**Comment by owennewo** [comment]
I'm trying your tool with a 2 stack using 0.5 nozzle and 0.4mm layer height.   From my limited Cura experience, the stl looked good when I examined the intersection, so I have some confidence that it should separate.  It's possible that I might run into problems unrelated to your STL (thermal creep) as my ender3 pro doesn't enjoy printing out this fast!  
FYI My last dual was 5hrs 15mins (0.5/0.25) and this is 3hrs 30min (0.5/0.4mm).  
Longer term I'd probably slow it down to 0.5/0.35 to give me a quad in 8 hours whilst I sleep but I'm not sure whether it's best for layer height to be a nice multiple of 20mm.

**Comment by sebleedelisle** [comment]
> not sure whether it's best for layer height to be a nice multiple of 20mm.

With the new tool, the face shield height is adjusted to be a perfect multiple of whatever layer height you select, so you should be fine whatever you choose. But let me know!

**Comment by sebleedelisle** [comment]
I'm gonna close this for now, let me know if you have trouble and I'll reopen it.

**Comment by owennewo** [comment]
Sad face. This was 0.5/0.4mm.
![IMG_20200411_201203](https://user-images.githubusercontent.com/15650427/79052817-0194eb80-7c31-11ea-97c3-dcab911d9581.jpg)

**Comment by owennewo** [comment]
I think there is a dot missing in the model.  On the prusa stack there is a second dot in the center of the attached image (Prusa has 8 dots, yours has 7).  Yours is missing that dot.
![missing_dot](https://user-images.githubusercontent.com/15650427/79053153-fe9afa80-7c32-11ea-8d5c-977e17a8a9e1.png)

**Comment by sebleedelisle** [comment]
I did add these in a recent update but they maybe too small to come out at large layer heights. Can you check again and let me know?

**Comment by sebleedelisle** [comment]
Also, I only count 5 "dots" on both the Prusa model and also ours...

**Comment by owennewo** [comment]
There are 8 dots on prusa.  Attached are two prusa and two seblee images.  prusa_left_dots one has three dots, whereas seblee_central_dots has two (missing top left).  prusa_central_dots has two dots but seblee_central has one dot (missing central bottom).  Haven't bothered with right images as its just a mirror of left
![seblee_central_dots](https://user-images.githubusercontent.com/15650427/79064334-f7f69c80-7c9f-11ea-93a0-6210ec41b3f6.png)
![seblee_left_dots](https://user-images.githubusercontent.com/15650427/79064335-f88f3300-7c9f-11ea-864f-8ae74a1af420.png)
![prusa_central_dots](https://user-images.githubusercontent.com/15650427/79064336-f927c980-7c9f-11ea-9fea-870e09c28397.png)
![prusa_left_dots](https://user-images.githubusercontent.com/15650427/79064337-f9c06000-7c9f-11ea-951a-61dd239aecf0.png)

**Comment by sebleedelisle** [comment]
Got it, thanks 😊
