### ISSUE TITLE
Problem with infill using S3D to slice

### ISSUE THREAD

**Issue by rsmith21** [paulhayes/web-3d-model-customiser#23]
I added my details and downloaded the file without problems,but when I slice it the print preview shows infill between the visor support and head band.

**Comment by sebleedelisle** [comment]
Hey Bob, not quite sure what you mean, what do you mean by "visor support"?  - can you do a screen grab or something?

**Comment by rsmith21** [comment]
![image](https://user-images.githubusercontent.com/4954805/78680036-e3528700-78e2-11ea-9d88-4e89891db1c4.png)
Also if I use Cura it tells me the file has holes, so I use the mesh tool to repair, but it still shows red for an error.

**Comment by sebleedelisle** [comment]
Huh I never saw that before. Has that just started happening or is this the first time you tried it? I just pushed an update an hour or so ago.

**Comment by sebleedelisle** [comment]
Also, can you let me know what settings you used, we'll try to replicate the error. Also, send me the STL - thanks!

**Comment by rsmith21** [comment]
I don't think its new, I tried it when you first made it available, when I saw the problem I went back to standard printing to get the job done.

**Comment by rsmith21** [comment]
The file you base the headband on, is that an STL , or the Prusa one.

**Comment by sebleedelisle** [comment]
it's based on the Prusa STP file

**Comment by rsmith21** [comment]
That is my problem, when I use that it also looks wrong, but if I use their STL it slices perfectly.Sorry to give you unnecessary grief, I should have realised.

**Comment by sebleedelisle** [comment]
Which version of Cura? I'll download it and take a look. It'd be good if we can get it sorted!

**Comment by rsmith21** [comment]
4.5 , would it be possible to base the system on the STL, or an option to use STP or STL.

**Comment by sebleedelisle** [comment]
I'll look into it - thanks

**Comment by sebleedelisle** [comment]
Just tried in Cura 4.5, don't seem to have the problem... could it be some kind of raft/brim setting? 
![Screenshot 2020-04-07 at 15 57 21](https://user-images.githubusercontent.com/110866/78684597-907bce00-78e8-11ea-94c7-ebfa3f82b52f.png)

**Comment by rsmith21** [comment]
I'll load the STP and see how it shows on mine, I normally only use the STL since my printers are not Prusa.

**Comment by sebleedelisle** [comment]
the image above is from an STL created by our system

**Comment by Matt2k34** [comment]
This happens to me if I use the STL from the prusa site within cura. It does NOT happen for me for the STLs generated by the customizer.

@rsmith21 can you confirm you're using the customised (auto dated) STL?

**Comment by rsmith21** [comment]
![image](https://user-images.githubusercontent.com/4954805/78692877-6e874900-78f2-11ea-9291-17dae95088ff.png)
Cura didn't open the STP file for me, I opened the 3MF file and this is what I get, in a sliced preview.

**Comment by Matt2k34** [comment]
The customizer doesn't generate a 3mf. That is from the prusa site (which is broken in cura)

**Comment by sebleedelisle** [comment]
I'm also seeing the issue when loading the Prusa 3mf file. @rsmith21 can you send me your STL that your getting from our system that's causing the problem? Thanks!

**Comment by rsmith21** [comment]
I tried to drag and drop the file but get the error " we don't support that kind of file"

**Comment by rsmith21** [comment]
I'm sure that if no one else is having a problem slicing the file its a setting I have, please don't waste any time on it. I can get by for now without embossing or use the 3D builder method. 
Thanks for looking at it, will I just close it.

**Comment by sebleedelisle** [comment]
I'm wondering if it's a bug that only appears with your particular choice of name or quality. Does it still happen no wonder how you customise the file?
