### ISSUE TITLE
Date mismatch leaving if I leave page open overnight

### ISSUE THREAD

**Issue by RikAllen** [paulhayes/web-3d-model-customiser#27]
Minor point. 
Having left a browser open at this page overnight (opened page on 8/4/2020), when I go to generate the next days stack by adding one on the pull down, the user interface says "+1 9/4/2020". The downloaded model gives a different date of 10/4/2020. 

Easy to fix with a page refresh, but threw me a bit.

**Comment by paulhayes** [comment]
Ah yes, classic. Thanks for letting us know.

**Comment by paulhayes** [comment]
Fixed in cbdc4d4b337f9377f6ce54b9afea1ce160331f0a
