### ISSUE TITLE
Adjustable layer height setting

### ISSUE THREAD

**Issue by Vegsaad** [paulhayes/web-3d-model-customiser#30]
Most people are printing with larger nozzles to increase print speed and productivity. When I tried a two-stack with a 0.8mm they welded together and could not be separated without scrapping both parts. Adding an option to increase the gap by either directly entering the Gap size or indirectly by entering the nozzle size would solve this and allow it to be printed fast and in numbers overnight unattended. Great work so far - thanks!

**Comment by sebleedelisle** [comment]
Hi there, I'm currently testing the layer height setting, can you give it a try and report back? https://modsebleedev.netlify.com

**Comment by sebleedelisle** [comment]
Closing this for now, let me know how it works for you.

**Comment by Vegsaad** [comment]
Will do thanks.
