### ISSUE TITLE
outside pins are stuck to support wall in mulstistack

### ISSUE THREAD

**Issue by ales1** [paulhayes/web-3d-model-customiser#34]
One more suggestion please, in stacked version there is extra support printed on the front for the pins. I have a problem removing the support on external pins, middle two pins seems to only touch the base, but side pins do touch support walls on the side and stick to them pretty well, expanding those by 1mm would solve the problem

**Comment by sebleedelisle** [comment]
What layer height and extrusion width are you printing in please?

**Comment by ales1** [comment]
Hey, layer height is 0.3. Extrusion width is a default 0.4 mounted on flsun qq s.

**Comment by paulhayes** [comment]
Ha we have the same printer!

**Comment by ales1** [comment]
nice one:) there is a channel on slack printersettings-flsun-qq-s if you want to join.  this is my second week printing, never did that in a past. If you have any expierience please share. Have you managed to do reasonable prints in PETg?

**Comment by twistedsanity** [comment]
I'm having the same issue, the outside pins are closer to the rear wall of the support (offset) and when running high speed with larger width (to reduce print time) it sticks. The middle 2 pins are fine as they are evenly spaced but the edge two aren't. I would love it if you were just able to tweak it slightly to even it up, and maybe add an extra 0.2. 
That being said, awesome work!!!! thank you!

**Comment by sebleedelisle** [comment]
Hopefully fixed in the current dev version ( http://modsebleedev.netlify.com ) - can you try it out and let me know? You can check the layer height feature while you're there 😊

**Comment by ales1** [comment]
Printing the last one in current stack, will try on next go

**Comment by sebleedelisle** [comment]
Closing this for now, let me know if you still have trouble and I'll reopen it.

**Comment by ales1** [comment]
hey,
just finished a stack of 3, another small fix is needed.
Looking from the front (so you see all those pins in front of you). Left pin didn't have adhesion to the support walls anymore, two middle as good as in the past, but right one I would say even worse.
Exactly the same on both examples from the same stack, level 0 & 1

**Comment by sebleedelisle** [comment]
Hi there, thanks for the feedback. Did you have "detect thin walls" switched on? 
What do you mean by pins? What do you mean by support walls? Sorry but it's hard to understand when there's no standardised terminology!

**Comment by ales1** [comment]
Hey Seb, I use Cura and I didn't have 'think wall' option selected, will do another stack of three soon will confirm here. And will try to be more specific with description or even a picture. Thanks!
