### ISSUE TITLE
Flashprint Import Issues

### ISSUE THREAD

**Issue by StuartWaudby** [paulhayes/web-3d-model-customiser#35]
Hello, great job, thank you. Running with no issues on Simplify 3D.

Import in to Flashforge's Flashprint results in a model error. Any attempt to slice with or without repairing gives unusable results.
![Flashprint bug](https://user-images.githubusercontent.com/63495080/79039798-9cfb7180-7bdb-11ea-8250-5aec6f03b244.JPG)
![Flashprint Import](https://user-images.githubusercontent.com/63495080/79039813-c7e5c580-7bdb-11ea-8c01-fbdc34c89a4f.JPG)

**Comment by sebleedelisle** [comment]
Unfortunately the models exported are non-manifold, we're not sure why but it's something to do with the underlying OpenJsCad library we're using. It's not a problem for most slicers though. If you desperately need to use FlashPrint, I would recommend fixing the models with Netfabb (or even by loading and exporting from PrusaSlicer). 

Sorry I can't be more help!
