### ISSUE TITLE
Add bottom reinforcement parts

### ISSUE THREAD

**Issue by krisnoble** [paulhayes/web-3d-model-customiser#38]
Another QOL suggestion, would it be possible to have an option add in the relevant number of the chin piece model as well?

Thinking it would make it to make it easier for newbies to get started, since this tool seems to be the de facto "start here" suggestion whenever anyone asks.

**Comment by sebleedelisle** [comment]
I must admit this feature was in the back of my mind anyway. Thanks for making it official 😊

**Comment by sebleedelisle** [comment]
Now implemented on the dev server http://modsebleedev.netlify.com - will be merged into the main site soon.
