### ISSUE TITLE
Material choice does not update the model correctly

### ISSUE THREAD

**Issue by dom-white** [paulhayes/web-3d-model-customiser#40]
Material choice does not update the model correctly anymore,

For me it always generates a model with the default PETG label

**Comment by dom-white** [comment]
![image](https://user-images.githubusercontent.com/16900548/79048996-cc7c9f00-7c18-11ea-8ae2-10c2870287a4.png)

**Comment by paulhayes** [comment]
Sorry, my mistake, I'll fix immediately.

**Comment by paulhayes** [comment]
Fixed

**Comment by dom-white** [comment]
Thanks for the quick fix. Great resource BTW
