### ISSUE TITLE
Pin support structure is broken with 0.6mm line width (but good at 0.5)

### ISSUE THREAD

**Issue by owennewo** [paulhayes/web-3d-model-customiser#41]
Pictures say a thousand words! Here are two from cura.  The only difference is line width.  If you take a look at the "0.6mm line width" picture the support round the two central pins has lost most of the lines and hence ends up as string when printed.  The "0.5mm line width" looks fine.

Note: This was using your new 'dev' version with variable layer height set to 0.4.  But it also looks 'bad' when layer height is standard 0.25mm

![broken_06mm](https://user-images.githubusercontent.com/15650427/79052503-dc9f7900-7c2e-11ea-86c8-e27b50bd4b47.png)
![good_05mm](https://user-images.githubusercontent.com/15650427/79052510-e3c68700-7c2e-11ea-90bc-45b1b035fb9f.png)

**Comment by sebleedelisle** [comment]
I might look at this in future but for now can you fix this by turning on the "print thin walls" setting
