### ISSUE TITLE
Support for the pins is to close (stacks)

### ISSUE THREAD

**Issue by 256FF** [paulhayes/web-3d-model-customiser#45]
After slicing my stratasys insight combines the support and the shield because the distance is to small.

![support](https://user-images.githubusercontent.com/20856957/79961334-dad38200-8486-11ea-8708-6949d5a7b73e.jpg)

**Comment by sebleedelisle** [comment]
This should be fixed in the dev version of the site, currently up for testing at modsebleedev.netlify.com - give it a try and let me know if you're still having problems.
