### ISSUE TITLE
V2 JSCAD

### ISSUE THREAD

**Issue by z3dev** [paulhayes/web-3d-model-customiser#55]
Awesome project! Thanks for using JSCAD.

It's time to move forward with V2 JSCAD, including the new modeling (CSG) package.

Please see www.jscad.xyz

**Comment by paulhayes** [comment]
> Awesome project! Thanks for using JSCAD.
> 
> It's time to move forward with V2 JSCAD, including the new modeling (CSG) package.
> 
> Please see [www.jscad.xyz](http://www.jscad.xyz)

Great, thanks for letting us know
