### ISSUE TITLE
Brim ears on the 

### ISSUE THREAD

**Issue by james-fry** [paulhayes/web-3d-model-customiser#9]
Is it possible to add an option for mouse ears on the ends?
e.g.
![image](https://user-images.githubusercontent.com/5823294/78459247-9e92da00-76af-11ea-8208-70461230494a.png)

Of course can be added in cad or slicer but it might help...

**Comment by sebleedelisle** [comment]
Hey James, is this to help with bed adhesion? Have you found it necessary? I must admit I haven't seen anyone else mention it but if it turns out to be popular I would consider it.

**Comment by james-fry** [comment]
Hi Yes - to prevent the print lifting from the the bed on the corners. Like a mini brim.
There are a number of people recommending it on the 3dcrowd.uk slack.
Since I have issues with this type of lifting I added on my prints and its working well.

![image](https://user-images.githubusercontent.com/5823294/78460641-6775f600-76ba-11ea-807c-afbb383f2665.png)

**Comment by sebleedelisle** [comment]
Good to know. I’ll definitely consider adding it 👍

**Comment by sebleedelisle** [comment]
Done 😊 #14

**Comment by james-fry** [comment]
Thanks Seb - it works great!
